# Generated by Django 2.1.1 on 2018-10-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry_web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_user', models.CharField(max_length=200)),
                ('enquiry_email', models.EmailField(max_length=200)),
                ('enquiry_number', models.IntegerField(max_length=200)),
                ('enquiry_area', models.CharField(max_length=200)),
                ('enquiry_budget', models.IntegerField(max_length=200)),
                ('enquiry_type', models.CharField(choices=[('Private Room', 'Private Room'), ('Shared Room', 'Shared Room')], max_length=20)),
                ('enquiry_comment', models.TextField(max_length=500)),
            ],
        ),
    ]
