# Generated by Django 2.1.1 on 2018-10-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_web',
            name='enquiry_comment',
            field=models.TextField(max_length=500),
        ),
    ]
