# Generated by Django 2.1.1 on 2018-09-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyRegistration', '0003_auto_20180928_0719'),
        ('PropertyRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_registration',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CompanyRegistration.Company_Registration'),
        ),
    ]
