# Generated by Django 2.1.1 on 2018-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyRegistration', '0002_property_registration_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_registration',
            name='Gender',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
