# Generated by Django 2.1.1 on 2018-09-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyRegistration', '0004_auto_20180928_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_registration',
            name='pg_url',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
