# Generated by Django 2.1.1 on 2018-09-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyRegistration', '0005_property_registration_pg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_registration',
            name='Gender',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=255),
        ),
        migrations.AlterField(
            model_name='property_registration',
            name='pg_url',
            field=models.CharField(max_length=1000),
        ),
    ]
