# Generated by Django 2.1.1 on 2018-10-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181001_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
