# Generated by Django 2.1.1 on 2018-10-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_registration',
            name='city',
        ),
        migrations.AddField(
            model_name='company_registration',
            name='city',
            field=models.ManyToManyField(to='CompanyRegistration.City'),
        ),
    ]
