# Generated by Django 2.1.1 on 2018-09-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_registration',
            name='Rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_registration',
            name='Review',
            field=models.CharField(choices=[('Very Good', 'Very Good'), ('Normal', 'Normal'), ('Bad', 'Bad')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_registration',
            name='company_address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
