# Generated by Django 2.1.1 on 2018-09-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyRegistration', '0002_auto_20180928_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_registration',
            name='Review',
            field=models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Normal', 'Normal'), ('Bad', 'Bad')], max_length=20),
        ),
    ]
